PowerShell/DscResource.Tests

- MetaFixers.psm1
> Replace Set-Content by WriteAllText to avoid new lines at the end

- README.md
There were a couple spelling and grammar nits in the readme.
> Fix spelling and grammar in readme.md

- TestHelper.psm1
In a couple of places we have Write-Verbose -Verbose this forces the verbose string to be displayed regardless of parameters specified when the funciton is called.
Also TIL that this works this way, lol.
> Modifying Verbose Flags

- Meta.Tests.ps1
- MetaFixers.psm1
> Fix encoding error message for MOF files

- Meta.Tests.ps1
- MetaFixers.psm1
Reverts PowerShell/DscResource.Tests#33
This probably should not go in until the existing issues are fixed.
> Revert "Resolves #31, Added test and fixer for text files ending with new lines"

- Meta.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/38)
> Fix exception occuring when a single PSSA rule violation occurs - Fixes #37

- Meta.Tests.ps1
- MetaFixers.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/36)
> Resolves #31, Added test and fixer for text files ending with new lines

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/39)
> Update links to test guidelines. Fixes #34

- DscResourceCommonTests/DscResourceCommonTests.psd1
- DscResourceTestHelper/DscResourceTestHelper.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/49)
> Releasing 0.2.0.0 of DscResourceCommonTests and DscResourceTestHelper

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/50)
> Merging version release notes into master

- TestHelper.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/51)
> fixing path to go into subfolder

- DscResourceTestHelper/TestHelper.psm1
- TestHelper.psm1
we will be deletng DscResources.Test/TestHelper.psd1 once all modules are updated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/52)
> fixed the previous path-problem in the wrong file

- TestHelper.psm1
Also displays the detected path of the DSC Resource Module root folder in the host. If the DSC Resource Module is detected as the root of the disk (e.g. C:\) or it couldn't be detected at all, an exception will be thrown and the $ENV:PSModulePath will not be updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/65)
> Improve detection of DSC Resource Module root folder in Initialize-TestEnvironment - Fixes #55

- Meta.Tests.ps1
- MetaFixers.psm1
- README.md
- TestHelper.psm1
- TestRunner.psm1
Hi, simple change, I have replaced any instances of aliases in the files with the correct command.
Also replaced double quotes with singles quotes where needed
Tested here: as per this appveyor build https://ci.appveyor.com/project/nzspambot/xwebadministration/build/1.11.111.0 using this file https://raw.githubusercontent.com/nzspambot/xWebAdministration/UpstreamTestFixes/appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/62)
> Removed aliases from files

- TestHelper.psm1
Please see discussion here:
https://github.com/PowerShell/DscResources/issues/172
- Added Reset-DSC function.
- Changed Initialize/Restore-TestEnvironment functions to call Reset-DSC if Integration tests running.
- Fixed Restore-TestEnvironment so that Integration tests reset environment correctly.
I have tested this against xNetworking and xTimezone and it seems to work correctly and doesn't change the test behaviour. A new message will appear before and after integration tests if the LCM is not currently processing a document. But that is just fine I think:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/72)
> Add Reset-DSC Function to TestHelpers Module

- Meta.Tests.ps1
Fix for issue #77 - Adds logic to handle empty files in tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/78)
> Fix for issue #77 - Adds logic to handle empty files in tests

- DscResource.DocumentationHelper/PowerShellHelp.psm1
- DscResource.DocumentationHelper/WikiPages.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/95)
> Silently continue if no examples are found

- Meta.Tests.ps1
- TestHelper.psm1
Fixes #118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/119)
> Fixes Get-ClassResourceNames for #118

- DscResource.CodeCoverage/CodeCovIo.psm1
publish the codecov upload log
Fixes #127 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/126)
> Use git ls-file to determine the codecov file key

- README.md
Fixes #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/283)
> Removed sections 'Goals' and 'Git and Unicode'
