- Meta.Tests.ps1
Meta.Tests.ps1 has been updated to run Test-xDscResource and Test-xDscSchema from the xDscResourceDesigner module for all non-composite DSC resources as suggested by @KarolKaczmarek in PR https://github.com/PowerShell/xAzure/pull/5.
1. Download and install the latest stable xDscResourceDesigner module from the PowerShell Gallery using nuget.exe to stay compatible with WMF v4 machines where the Package Management module is not available.
2. Changed how DSC resource modules in the child folder DscResources are being discovered to exclude library modules like in xJea because the *.schema.mof is not present.
3. Expanded aliases and replaced double quotes to single quotes were applicable.
Please be so kind to review and pull the changes if you are happy.
> Fixes #3. Added logic to always run Test-xDscResource and Test-xDscSchema for all non-composite DSC resources

- Meta.Tests.ps1
- README.md
- TestHelper.psm1
This should fix Issue #8.
The following changes were made:
1. Code to download xDSCResourceDesigner moved from Meta.Tests.ps1 into Get-ResourceDesigner function of TestHelper.psm1
2. If PowerShellGet module installed: xDSCResourceDesigner downloaded using Install-Module.
3. If PowerShellGet Module not installed: xDSCResourceDesigner install using Nuget.exe.
4. No longer uses Start-Process to call out to Nuget.exe.
5. xDSCResourceDesigner only downloaded automatically when running in AppVeyor.
6. xDSCResourceDesigner Module imported using Name only (not path) so that it works when installed via PowerShellGet.
7. Added some AppVeyor config samples and other details into the Readme.md.
I've thrown this through a lot of tests on projects using both Windows Server 2012 R2 and Unstable AppVeyor …
> Fixed xDscResourceDesigner blank exit code installation failures. Fixes #8

- TestHelper.psm1
Install-ModuleFromPowerShellGallery has a verbose string that is coming back as such:
```powershell
VERBOSE: Version System.Object[] of the xDscResourceDesigner module is already installed.
````
This is a modification to correctly come back with the version number as designed.
> Modifying Verbose String

- TestHelper.psm1
This is a fix to issue #19.
It resolves errors caused when a local testing machine has more than one version of the PSScriptAnalyzer module installed.
Until this is installed, any errors caused by multiple PSScriptAnalyzer modules can be resolved by just removing any older versions of PSScriptAnalyzer. So this is not a critical issue.
Thanks!
> Making sure Install-ModuleFromPowerShellGallery returns only one record. Fixes #19

- Meta.Tests.ps1
This resolves issue #18.
@vors or @TravisEz13 - could one of you possibly take a look at this while @KarolKaczmarek is away? It is not super critical, but would be nice to get it fixed because at the moment the PSScriptAnalyzer error output isn't visible at all.
This change causes PSScriptAnalyzer output now shows like this:
I changed all the Write-Error to Write-Warning, because Write-Error causes an exception to be thrown and then control jumps straight to the "Should Be", which skips means that the remaining messages are never output.
Also corrects (due to ISE Steroids warnings):
1. Double quotes changed to single quotes for strings not containing any variables.
> Output PSScriptAnalyzer results correctly when more than one record. Fixes #18

- README.md
- TestHelper.psm1
- Fixes #57 
- Fixes #59 
Extra whitespace was also trimmed from the end of lines in Readme.md and TestHelper.psm1. This is a great feature of Visual Studio Code (but obviously slightly irritating for PRs the first time it is used).
I'm also not sure of what is happening with the Master branch of this repo because it has the subfolder structure in place. @mbreakey3 - are you able to advise if I'm committing this PR to the correct branch?
Once this PR is in place I'll look at #58 and #55 - just didn't want to be changing too many things in one go.
I have used this version in full tests using xNetworking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/60)
> Change Initialize-TestEnvironment to loads Module in Global Scope - Fixes #59

- TestHelper.psm1
This changes the Initialize-TestEnvironmet and Restore-TestEnvironment so that the Machine level Environment variable for PSModulePath is set only when executing Integration tests. Unit tests will only set the process level PSModulePath.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/67)
> Only integration tests will change the Machine PSModulePath - Fixes #55

- README.md
- TestHelper.psm1
When calling the `Initialize-TestEnvironment` function as an unprivileged user, the following exception is thrown when by `Set-ExecutionPolicy`: 
`UnauthorizedAccessException: Access to the registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' is denied.`
Unprivileged users do not have the rights to modify the execution policy globally for the system. I changed the calls to `Set-ExecutionPolicy` to limit the scope of the change to the current process.
`Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope Process -Force`
This change was required in both `Initialize-TestEnvironment` and `Restore-TestEnvironment`.
> Allow initialization and restoration of test environments for unprivileged users

- Meta.Tests.ps1
- TestHelper.psm1
- Added function to detect Class resource name from psm1 files
- Added test to validate minimum PowerShell version specified in Root Module manifest (4, 5 or 5.1)
- Added test to validate Class resources exported in Root Module manifest
- Added test to validate Class resource modules are specified as nested modules in Root Module manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/76)
> Added additional tests to deal with Class resource / Mixed resource modules

- Meta.Tests.ps1
- MetaFixers.psm1
- README.md
- TestHelper.psm1
- TestRunner.psm1
There was a test break in PSDscResources due to a bad function call (Test-ModuleManifest) in one of the common tests.
While I was fixing that test, I also cleaned up all the other common tests along with the other modules provided in this repo.
I also added some new tests to check for PS Script Analyzer DSC Resource Kit required/flagged rules as well as rule suppressions of required rules.
3 of these tests (the ones that check for required, flagged, and other error rules) currently pass automatically, but they will print out warnings in AppVeyor. The automatic passes are in place to give people time to fix the errors coming from those tests before we turn them on sometime around the beginning of 2017 (Jan-Feb).
One of the biggest changes here is that I have removed the 'Working Directory' …
> Clean common tests and modules and add tests for PS Script Analyzer

- Meta.Tests.ps1
- README.md
- TestHelper.psm1
Updating the common test output to split the PSSA tests and file parsing tests by file.
This is required for xDscDiagnostics (which doesn't actually contain any resources) to pass the common tests.
Other modules should not be affected.
@mbreakey3 Please review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/80)
> Update common test output format

- TestHelper.psm1
This corrects the removal of the ".schema" from the resource name so that it is case insensitive.
Because I'm using VSCode with automatic trimming of redundant white space enabled it has cleaned the file up as well (I wish more people used this function :grin: ).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/82)
> Fix Get-ModuleScriptResourceNames - Fixes #81

- TestHelper.psm1
Found use cases where I forgot to add line breaks at the end of a few files.  Adding in handling for those to capture the failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/83)
> Adding files to the text file extensions list.

- Meta.Tests.ps1
This PR fixes #96 so that the markdown test correctly scan all markdowns in xNetworking and SharePointDsc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/97)
> Fix Detection of Repo Root folder in Meta.tests.ps1 - Fixes #96

- Meta.Tests.ps1
This PR fixes the error occurring when trying to remove the Markdown results file when it doesn't exist.
This also corrects the code style to meet the standard guidelines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/113)
> Fix Error Message when NPM not available but Markdown tests enabled - Fixes #112

- DscResource.DocumentationHelper/WikiPages.psm1
- README.md
This PR contains the following changes:
* Fixed Wiki Generation to create Markdown that does not violate markdown rules
* Removed violation of markdown rules from Readme.md
I also fixed up all the Markdown violations in the Readme.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/131)
> Change Wiki Generation to create valid Markdown Files - Fixes #130

- AppVeyor.psm1
- README.md
- Changes to AppVeyor
-  Added so that any error message for each test are also published to the AppVeyor "Tests-view".
There was some spaces that was removed as well when I saved the file in VS Code (have auto-trim enabled). So there are a few rows that was changes because of that.
This branch was used to mock fails: 
https://github.com/johlju/xSQLServer/tree/appveyor-test
Test run here and example in screenshot:
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.558.0/tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/137)
> AppVeyor: Added failure message to be published to "Tests-view" - Fixes #138

- Meta.Tests.ps1
- README.md
Added a common test to verify so that no markdown files contains Byte Order Mark (BOM) (issue #108).
Tested here:
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.570.0/tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/139)
> Added a common test to verify so that no markdown files contains BOM - Fixes #108

- Meta.Tests.ps1
- README.md
I recently came across a bug that was being causes by long file paths in the "node_modules" path when the AppVeyor builds were copying the module to the system modules directory - it would throw the PathTooLongException. To avoid this I've made a small update here to get it to ignore the node_modules folder as it shouldn't be needed here anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/134)
> Fix to ignore node_modules path in build

- Meta.Tests.ps1
- TestHelper.psm1
On PSCore, the PowerShell paths are under "...\PowerShell\..." instead of "...\WindowsPowerShell\...".
Added Get-PSModulePathItem to handle those differences.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/154)
> Using module path in PS Core

- AppVeyor.psm1
- README.md
- Changes to AppVeyor.psm1
- Changed debug message which outputs the type of the $results variable (in AppVeyor.psm1) to use Write-Verbose instead of Write-Info (issue #99).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/165)
> Changed debug message which outputs the type of the $results variable - Fixes #99

- Meta.Tests.ps1
- README.md
- TestHelper.psm1
This PR adds support to identify any dependent modules in Example files (that aren't the module being tested) and will either warn the user they're required (tests will still fail) or if running in AppVeyor will install the module from the PS Gallery.
I added a new function `Get-ResourceModulesInConfiguration` that does the work of extracting any resource modules required in a DSC Configuration. It uses the PowerShell AST for this, but I do have an alternate method using RegEx around that I could use if the AST method isn't to taste.
This is a recreation of PR #158 because I some how messed up the rebase. Sorry about that.
@johlju - are you able to check this off again for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Add check for dependent modules in Examples and Warns user or installs - Fixes #157

- .MetaTestOptIn.json
- Meta.Tests.ps1
- README.md
Added new common test so that script files (.ps1) are checked for Byte Order Mark (BOM) (issue #160). This test is opt-in using .MetaTestOptIn.json.
This is tested OK here: 
https://ci.appveyor.com/project/johlju/xsqlserver/build/6.0.786.0#L60
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/164)
> Added new common test checking script files for BOM - Fixes #160

- DscResource.AnalyzerRules/DscResource.AnalyzerRules.psd1
- DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1
- DscResource.AnalyzerRules/en-US/DscResource.AnalyzerRules.psd1
- Meta.Tests.ps1
- README.md
This PR adds a new PS Module called DscResource.AnalyzerRules. It contains an initial set of rules for validating resources against the style guidelines and minimum standards for the DSC Resource kit.
These rules are applied like any other PSSA rules, but will currently not cause a test failure if any are violated. Once https://github.com/PowerShell/DscResource.Tests/issues/161 is addressed then we should be able to opt-into triggering failures on these rules.
I've only included only one rule currently (validate the [Parameter()] attribute exists and is formatted correctly) - which can generate 3 different violations. Separating these into different rules results in much slower processing and doesn't really add anything useful IMHO.
I wanted to start really small on this so we'll need to …
> Add basic custom PSSA rules support for validating Resource Kit guidelines - Fixes #86

- DscResource.AnalyzerRules/DscResource.AnalyzerRules.psd1
- DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1
- DscResource.AnalyzerRules/en-US/DscResource.AnalyzerRules.psd1
- README.md
- Changes to DscResource.Tests
- Fixed Byte Order Mark (BOM) in files; DscResource.AnalyzerRules.psd1,
DscResource.AnalyzerRules.psm1 and en-US/DscResource.AnalyzerRules.psd1 (issue #169).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/171)
> Fixed Byte Order Mark (BOM) in files - Fixes #169

- AppVeyor.psm1
- README.md
- Tests/Unit/AppVeyor.Tests.ps1
* Added ```Invoke-AppveyorTestScriptTask``` cmdlet functionality for CodeCoverage for Class based resources ([issue #173](https://github.com/PowerShell/DscResource.Tests/issues/173))
* Added tests for module ```AppVoyer.psm1``` and tested ```Invoke-AppveyorTestScriptTask``` to verify it adds all the folders needed for CodeCoverage when running ```Invoke-Pester```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/dscresource.tests/212)
> Added CodeCoverage for Class based resources - Fixes #173

- DscResource.AnalyzerRules/DscResource.AnalyzerRules.psm1
- Meta.Tests.ps1
- README.md
- TestHelper.psm1
- Tests/Unit/DscResource.AnalyzerRules.Tests.ps1
- Tests/Unit/TestHelper.Tests.ps1
This addresses #265, where custom PSSA rules were not returning a value for the RuleName property.  This previously prevented custom rules from being suppressed using SuppressMessageAttribute.  
With this change, each rule uses the same property name that was being use for $localizedData and uses that for the RuleName.  This makes it easy for testing purposes and consistency throughout the module.  The rule name is also prefixed with the module name, so rule names look like this: 'DscResource.AnalyzerRules\ParameterBlockNonMandatoryParameterMandatoryAttributeWrongFormat'.
It is a bit verbose now, but is specific and now supports suppressing specific rules within the custom PSSA module like this:
`[System.Diagnostics.CodeAnalysis.SuppressMessageAttribute('DscResource.AnalyzerRules\Parameter …
> Adding rule name for custom rules
